### ISSUE TITLE
iter_metadata would unexpectly find another package's metadata

### ISSUE THREAD

**Issue by frostming** [sarugaku/requirementslib#186]
https://github.com/sarugaku/requirementslib/blob/d252fd07fa12df231ba8858ecf16215b936307c1/src/requirementslib/models/setup_info.py#L455-L473

`iter_metadata()` scans metadata that ends with given pattern inside a path **recursively**, which would return unexpected results in some cases, here is the directory tree of one:
```
├───.venv    # We have a .venv folder here
│   ├───Include
│   ├───Lib
│   │   └───site-packages
│   │       ├───pip
│   │       ├───pip-19.0.3.dist-info   # pip metadata will be returned
├───src
│   ├───requirementslib
...
```

Testing:
```python
r = requirements.Requirement.from_line('-e .')
print(r.ireq)
```
The possible solution is to change the DFS method to BFS.

**Comment by uranusjr** [comment]
I don’t have time to read the actual PR implementation, but using BFS sounds like the correct idea.

**Comment by techalchemy** [comment]
I believe I had this implemented at one time and it was terribly broken, but I could be mistaken. at a glance it seems right
