### ISSUE TITLE
In setup_info, comparator `contains` is called incorrectly

### ISSUE THREAD

**Issue by mgmarino** [sarugaku/requirementslib#225]
[operator.contains](https://github.com/sarugaku/requirementslib/blob/master/src/requirementslib/models/setup_info.py#L682) should be called with swapped operands.  See the [documentation](https://docs.python.org/3/library/operator.html#operator.contains).

**Comment by techalchemy** [comment]
woops, good catch -- thanks!

**Comment by techalchemy** [comment]
woops, good catch -- thanks!
