### ISSUE TITLE
pathlib2 pinning to 2.1.0 creates a version conflict with latest pytest 3.7.1

### ISSUE THREAD

**Issue by danygielow** [sarugaku/requirementslib#38]
The new pytest version 3.7.1 requires pathlib2 >= 2.2.0.

This leads to a version conflict with requirementslib, which I use for a release helper library to parse Pipfile.lock for some checks. That library also needs pytest.

Seeing as there is already a commit unpinning pathlib2, could you please release a new version containing that commit?

Many thanks in advance

**Comment by techalchemy** [comment]
Sure thing, sorry for the delay. Will try to cut a release later today

**Comment by techalchemy** [comment]
Apologies for the delay, this got caught up in a cascade of other related releases -- this is released now and should be all set
