### ISSUE TITLE
What does the “indexes” argument of “from_pipfile” do?

### ISSUE THREAD

**Issue by uranusjr** [sarugaku/requirementslib#6]
The `indexes` argument of `from_pipfile` does not do anything, and is simply dropped. Instead, `as_line()` takes an optional `project` argument to get the index. This is weird. I would expect an API like this instead:

```pycon
>>> indexes = [{'name': 'privatepi', 'url': 'http://localhost:1234/simple', 'verify_ssl': False}]
>>> from requirementslib import Requirement
>>> req = Requirement.from_pipfile(
...     name='requirementslib', indexes=indexes,
...     pipfile={'version': '*', index='privatepi'},
... )
>>> req.as_line(include_index=True)
requirementslib -i http://localhost:1234/simple
```

**Comment by techalchemy** [comment]
I think it’s just a list of urls. I’m open to changing it. By default you can just pass an empty list so the orde isn’t greet

**Comment by uranusjr** [comment]
The big problems are 1. `indexes` is not used at all, and 2. the `project` parameter doesn’t make sense outside of Pipenv.

**Comment by techalchemy** [comment]
That’s why it’s a list of urls. Indexes are used — when you output in pipfile format an index would be included if it exists and when you output as_line you can specify include_indexes. That formats them into pip arguments.
