### ISSUE TITLE
Markers in requirements.txt is not working for editable package

### ISSUE THREAD

**Issue by jxltom** [sarugaku/requirementslib#77]
Current pipenv or requirementslib will output editable package in ```requirements.txt``` like this ```-e git+https://github.com/requests/requests.git@883caaf145fbe93bd0d208a6b864de9146087312#egg=requests ; python_version == '2.7'```

But acutally markes such as ```python_version``` is not working. In python 3, requests will still be installed by ```pip install -r requirements.txt```

I found that in https://github.com/pypa/pip/issues/4530, it looks like the correct format should be ```-e "git+https://github.com/requests/requests.git@883caaf145fbe93bd0d208a6b864de9146087312#egg=requests ; python_version == '2.7'"``` with ```"``` quoted :cry:

**Comment by jxltom** [comment]
Oh, I just found that https://github.com/sarugaku/requirementslib/pull/71 may not the best solution.

I tested in pip18.1, ```-e "git+https://github.com/PyCQA/pylint.git@8682a220911a9c22286089e08f7e77b7b15d990b#egg=pylint; python_version >= '3.4'"``` works with quotes but without whitespace. Maybe this is the best solution for outputing editable packages with markers.

It will also be nice to add variaous tests on that but based on different major pip version such as ```9.0.1```, ```18.1```

**Comment by uranusjr** [comment]
AFAIK the quoted form is not standard, and #71 is probably the most compatible way. Also `-e` requirements is not standardised (I think), so it might be worthwhile to ask pip maintainers to clarify what is the preferred form for an external tool to generate.

**Comment by jxltom** [comment]
It sounds good to have a discussion with pip maintainers.

But for now at least the markers in ```-e some_editable_packages@ref#egg=somepackage ; some_marker = 'value'``` is definitely not working, though it can be parsed by requirementslib.

**Comment by techalchemy** [comment]
That was my whole point in the last discussion about this, but pip doesn't respect markers at all in editable dependencies (it fails in normal formats or ignores them I think?)
